function deg_new = convert_from_old_degrees_to_corrected_degrees(deg_orig)

monitor_info = hwwa.monitor_constants();

px = bfw.deg2px( deg_orig, struct(...
    'height', monitor_info.monitor_height_cm ...
  , 'distance', monitor_info.z_dist_to_subject_cm ...
  , 'vertical_resolution', monitor_info.vertical_resolution_px) ...
);

deg_new = bfw.px2deg( px, struct(...
    'height', hwwa.corrected_monitor_height_cm() ...
  , 'distance', monitor_info.z_dist_to_subject_cm ...
  , 'vertical_resolution', monitor_info.vertical_resolution_px) ...
);

end